### PR TITLE
fix(module: tabbar): typescript error

### LINKED ISSUE #750: Fails to compile: 'title' is defined as an accessor... TabPaneComponent
## Version
3.0.1

## Environment
Angular 10.1 Zorro mobile 3.0.1

## Reproduction link
[https://stackblitz.com/edit/angular-ivy-zsymf2?file=package.json](https://stackblitz.com/edit/angular-ivy-zsymf2?file=package.json)

## Steps to reproduce
$ ng new PROJECT_NAME
$ cd PROJECT_NAME
$ ng add ng-zorro-antd-mobile --i18n=en_US
$ ng serve

## What is expected?
The app should compile and serve

## What is actually happening?
App fails to compile:

ERROR in node_modules/ng-zorro-antd-mobile/tab-bar/tab-bar-item.component.d.ts:10:5 - error TS2610: 'title' is defined as an accessor in class 'TabPaneComponent', but is overridden here in 'TabBarItemComponent' as an instance property.

10     title: string;
       ~~~~~
## Other?
If I go to node_modules/ng-zorro-antd-mobile/tab-bar/tab-bar-item.component.d.ts and comment out the line 12 (title: string) the app compiles

<!-- generated by ng-zorro-mobile-issue-helper. DO NOT REMOVE -->

### PR DESCRIPTION
**Pull request by Eve-Sama**
close #750 
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd-mobile/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 750

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

File: components/tab-bar/tab-bar-item.component.ts [hunk 1]
```diff
@@ -17,8 +17,6 @@ export class TabBarItemComponent extends TabPaneComponent {
   @Input()
   key: string = '';
   @Input()
-  title: string = '';
-  @Input()
```
Comment (Mr-Eve) [inline components/tab-bar/tab-bar-item.component.ts:21]: TabBarItemComponent 继承自 TabPaneComponent
在 TabPaneComponent 中已经有了title的input与get set. 
那么 TabBarItemComponent 本身也就有了, 没必要重新声明一次.
本地跑过单测了, 全部成功, 项目也run了, title没出现异常.

**Review by fisherspy — APPROVED** [review]
